name: Sync Obsidian to dooja-site

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Obsidian repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.OBSIDIAN }}
          repository: doojia/obsidian
          ref: main
          path: obsidian

      - name: Checkout dooja-site repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.DOOJASITE }}
          repository: doojia/dooja-site
          ref: main
          path: dooja-site

      - name: Copy Obsidian files to dooja-site
        run: cp -R obsidian/. dooja-site/content/obsidian
      
      - name: Commit and push changes
        run: |
          cd dooja-site
          git config --global user.email "konstantin_dujia@outlook.com"
          git config --global user.name "doojia"
          git add .
          git commit -m "Sync Obsidian to dooja-site $(date +%Y-%m-%d_%H:%M:%S)"
          git push -f origin main
